SERVER = 'http://localhost:4723/wd/hub'
DEVICE_NAME = 'EMULATOR'
APP = 'ru.appkode.friendsclub.internal'
PLATFORM_NAME = 'Android'
PLATFORM_VERSION = '7.0'
START_BUTTON = '%s:id/welcome_controller_phone_button' % APP
PHONE_INPUT = '%s:id/phone_input_edit_text' % APP
OTP_CONTROLL = '%s:id/otp_confirmation_controller_phone_number' % APP
OTP_KEYBOARD = '%s:id/numeric_board_view_button' % APP
PROGRESS_BUTTON = '%s:id/progress_button_button' % APP
PASSWORD_TOOLBAR = '%s:id/password_input_controller_toolbar' % APP
PASSWORD_INPUT = '%s:id/password_input_controller_edit_text' % APP
NO_PASSWORD = '%s:id/password_input_controller_restore_password_button' % APP
PASSWORD_EYE = '%s:id/text_input_password_toggle' % APP
PASSWORD_FORGOT = '%s:id/password_input_forget_password_button' % APP
PROFILE_SKIP = '%s:id/profile_input_controller_skip_button' % APP
BARCODE = '%s:id/card_controller_barcode' % APP
CARD = '%s:id/card_layout_card' % APP
SHOW_BARCODE_BUTTON = '%s:id/card_controller_barcode_container' % APP
CARD_TAB = '%s:id/authorized_tabs_card' % APP
SALES_TAB = '%s:id/authorized_tabs_sale' % APP
MAP_TAB = '%s:id/authorized_tabs_map' % APP
TUTORIAL = '%s:id/tutorial_controller_background' % APP
CLOSE_CARD = '%s:id/card_controller_close_barcode' % APP
SALE_TOOLBAR = '%s:id/sale_list_toolbar' % APP
LOOKFOR = '%s:id/sale_download_weekly_catalog_button' % APP
SALES_LIST = '%s:id/sale_list_recycler_view' % APP
SALE_ITEM = '%s:id/sale_item_title' % APP
